#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions


rm -rf processor*
rm -rf log*
rm -rf 0
rm -rf postProcessing
