#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get the number of processors to run on from system/decomposeParDict
nProc=$(getNumberOfProcessors)

# Move previous logs to oldLogs directory
mkdir -p oldLogs
mv log.decomposePar oldLogs/log.decomposePar
mv log.pimpleDyMFoam oldLogs/log.pimpleDyMFoam
mv log.reconstructPar oldLogs/log.reconstructPar

./gendynmeshdict.py

runApplication decomposePar -latestTime

runParallel `getApplication` $nProc

runApplication reconstructPar

runApplication vorticity
runApplication R

rm -rf processor*

python "/home/pete/Google Drive/Python/OpenFOAM/send_email.py"

notify-send "OpenFOAM" "Simulation finished."

./perf.py
