#!/bin/sh

#SBATCH --time=48:00:00     # WALLTIME
#SBATCH -N24 	            # Number of nodes
#SBATCH --job-name UNH-RVAT-OpenFOAM
#SBATCH --account=FY140434  # WC ID 
#SBATCH -p ec               # Queue name

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp system/decomposeParDict.solve system/decomposeParDict

# Get the number of processors to run on from system/decomposeParDict
nProc=$(getNumberOfProcessors)

# Move previous logs to oldLogs directory
mkdir -p oldLogs
mv log.decomposePar oldLogs/log.decomposePar
mv log.pimpleDyMFoam oldLogs/log.pimpleDyMFoam
mv log.reconstructPar oldLogs/log.reconstructPar

python scripts/gendynmeshdict.py

#runApplication decomposePar -latestTime

runParallel `getApplication` $nProc

python -c "import processing; processing.log_perf()"

