#!/bin/sh

#SBATCH --time=12:00:00     # WALLTIME
#SBATCH -N1 	            # Number of nodes
#SBATCH --job-name UNH-RVAT-OpenFOAM
#SBATCH --account=FY140434  # WC ID 
#SBATCH -p ec               # Queue name

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication reconstructPar -newTimes
