#!/bin/sh

while :
do
    echo "Deleting unnecessary mean fields"
    find -name pMean.gz -not -path "./10*" -not -path "./9.98*" -delete
    find -name UMean.gz -not -path "./10*" -not -path "./9.98*" -delete
    find -name UPrime2Mean.gz -not -path "./10*" -not -path "./9.98*" -delete
    find -name nutMean.gz -not -path "./10*" -not -path "./9.98*" -delete
    find -name kMean.gz -not -path "./10*" -not -path "./9.98*" -delete
    sleep 5
done 

