#!/bin/sh

while :
do
    echo "Deleting unnecessary mean fields"
    find -name pMean -not -path "./10*" -not -path "./9.98*" -delete
    find -name UMean -not -path "./10*" -not -path "./9.98*" -delete
    find -name UPrime2Mean -not -path "./10*" -not -path "./9.98*" -delete
    find -name nutMean -not -path "./10*" -not -path "./9.98*" -delete
    find -name kMean -not -path "./10*" -not -path "./9.98*" -delete
    sleep 5
done 

